spring.application.name=ProjectApp

spring.mvc.hiddenmethod.filter.enabled=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/projectApp_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Mysqlsoftuni1@3
logging.level.org.hibernate.persister.entity=ERROR
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.transaction.jta.platform=none

external.api.base-url=http://localhost:8081
external.api.timeout=5000


spring.thymeleaf.cache=false


